In [2]:
import numpy as np

In [3]:
y_predicted =  np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [18]:
def mae(y_true,y_predicted):
    total_error = 0
    for yt, yp in zip(y_true,y_predicted):
        total_error += abs(yt-yp) 
    print("Total Error : ",total_error)
    mae = total_error / len(y_true)
    print("Mean Absolute Error : ",mae)
    return mae 
    

In [19]:
mae(y_true,y_predicted)

Total Error :  2.5
Mean Absolute Error :  0.5


0.5

In [21]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [23]:
np.log([0.0000001])

array([-16.11809565])

In [24]:
epsilon = 1e-15

In [26]:
y_predicted 

array([1, 1, 0, 0, 1])

In [27]:
y_predicted_new=[max(i, epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [29]:
y_predicted_new=[min (i,1-epsilon) for i in y_predicted_new]
y_predicted_new


[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [30]:
y_predicted_new=np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [ ]:
-np.mean(y_true * np.log (y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [36]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon)for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true * np.log (y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [38]:
log_loss(y_true, y_predicted)

17.2696280766844